### PR TITLE
Update Azure install guide

### PR DESCRIPTION
**Pull request by schnie**
Just a quick update - seems like things have changed.

### CODE REVIEW

**Comment by schnie** [comment]
@petedejoy whats the protocol for a little fix like this? Do we backport these types of things?

**Comment by paolaperaza** [comment]
Thanks for this @schnie. Does this correction apply to previous versions of the platform? I'd make the change you committed to the same file in the `next` folder - it's not published right now, but that's the one that'll eventually turn into the docs folder for the next LTS release.

Docs about new features etc. don't get backported and I'd say little fixes/typos don't _have_ to be backported to earlier versions but can be for general goodwill.

**Comment by schnie** [comment]
@paolaperaza I think it'd apply to any version past or future, at this point in time. @ianstanton what you think?

**Comment by ianstanton** [comment]
@schnie agree it would apply to past, present and future releases.

**Comment by paolaperaza** [comment]
@ianstanton @schnie Ok! For the Azure install doc specifically I just added this to the file in `next` and I think since it's an install doc and people shouldn't be installing an earlier version of Astro I'll stop there.

(We also recently cleaned up this doc and looks like we only applied those changes to 0.16 + next). I'll merge this! Thanks again.

**Pull request merged**
